spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flightSystem
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: raj242adk@gmail.com
    password: eyal znvy gjwp jxji
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
